
/**
 * Automatically generated by Zserio C++ extension version 1.2.0.
 */

#ifndef EXT_EXT_H
#define EXT_EXT_H

#include <zserio/BitStreamReader.h>
#include <zserio/BitStreamWriter.h>
#include <zserio/BitFieldUtil.h>
#include <zserio/CppRuntimeException.h>
#include <zserio/StringConvertUtil.h>
#include <zserio/PreWriteAction.h>
#include <zserio/OptionalHolder.h>

#include "ext/Type.h"
#include "ext/ValueChoice.h"
#include "host/Map.h"

namespace ext
{

class Ext
{
public:
    Ext();
    explicit Ext(zserio::BitStreamReader& _in);

    void initializeChildren();

    host::Map<ext::Type, ext::ValueChoice>& getMap();
    const host::Map<ext::Type, ext::ValueChoice>& getMap() const;
    void setMap(const host::Map<ext::Type, ext::ValueChoice>& map);

    size_t bitSizeOf(size_t _bitPosition = 0) const;
    size_t initializeOffsets(size_t _bitPosition);

    bool operator==(const Ext& other) const;
    int hashCode() const;

    void read(zserio::BitStreamReader& _in);
    void write(zserio::BitStreamWriter& _out,
            zserio::PreWriteAction _preWriteAction = zserio::ALL_PRE_WRITE_ACTIONS);

private:

    zserio::InPlaceOptionalHolder<host::Map<ext::Type, ext::ValueChoice>> m_map;
};

} // namespace ext



#endif // EXT_EXT_H
